pipeline {
    agent any

    environment {
        REGISTRY   = "docker.io/kube20"
        IMAGE_NAME = "test-local-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
        KUBECONFIG = "C:\\ProgramData\\Jenkins\\.kube\\config"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t %REGISTRY%/%IMAGE_NAME%:%IMAGE_TAG% -f app/Dockerfile ."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-cred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    bat "docker login -u %DOCKER_USER% -p %DOCKER_PASS%"
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                bat """
                docker push %REGISTRY%/%IMAGE_NAME%:%IMAGE_TAG%
                docker tag %REGISTRY%/%IMAGE_NAME%:%IMAGE_TAG% %REGISTRY%/%IMAGE_NAME%:latest
                docker push %REGISTRY%/%IMAGE_NAME%:latest
                """
            }
        }
        stage('K8s Connectivity Test') {
            steps {
                bat 'kubectl --kubeconfig="C:\\ProgramData\\Jenkins\\.kube\\config" get nodes'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                bat """
                kubectl --kubeconfig="C:\\ProgramData\\Jenkins\\.kube\\config" ^
                set image deployment/cicd-demo cicd-demo=%REGISTRY%/%IMAGE_NAME%:%IMAGE_TAG%
                """
            }
        }
    }
    post {
        success {
            echo "Pipeline completed successfully! 🚀"
        }
        failure {
            echo "Pipeline failed. Check logs for errors. ❌"
        }
    }
}
